nav:
  - Home:
>>>>>>> 97c88c6 (nav?)
=======
site_name: JuryMind AI
nav:
  - API Documentation:
      - api.md
>>>>>>> 5b4c25a (setting up navigation)
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
